services:
  postgres-db:
    image: postgres:18-alpine
    container_name: harc-postgres-container
    environment:
      POSTGRES_USER: harc_user
      POSTGRES_PASSWORD: harc_password
      POSTGRES_DB: harc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: